version: "3.9"

services:
  # ======================
  # Keycloak Database
  # ======================
  keycloak-db:
    image: postgres:15
    container_name: keycloak-postgres
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: Password123@
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  # ======================
  # Keycloak Server
  # ======================
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.1
    container_name: keycloak-1
    command: start-dev
    depends_on:
      - keycloak-db
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: Password123@
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: Password123@
    ports:
      - "8080:8080"

  # ======================
  # Django Database
  # ======================
  db:
    image: postgres:15
    container_name: django-postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - django_db_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  # ======================
  # Django API
  # ======================
  web:
    build: .
    container_name: su24_34_pos_api
    command: >
      bash -c "
      python manage.py migrate &&
      gunicorn su24_34_pos_api.wsgi:application --bind 0.0.0.0:8090
      "
    ports:
      - "8090:8090"
    env_file:
      - .env
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - db
    restart: always

volumes:
  keycloak_db_data:
  django_db_data:
  static_volume:
  media_volume:
